Create new components
soulhave/personal-financial-front-end pull request #2
Opened 2022-09-15 01:34 UTC by soulhave

2022-09-15 01:35 UTC, soulhave commented on src/app/components/template/header/header.component.html
> +        <mat-icon>menu</mat-icon>
@amorimluiz Da uma olhada neste cara aqui ... 
https://stackblitz.com/edit/so-angular-event-emitter?file=app/app.component.ts

Ele vai te ajudar a entender o que é o event emitter.
O Event emitter consegue fazer com que voce propague um evento de um component para outro.
No exemplo tem dois components. Um que gera um evento para o outro.

2022-09-18 20:27 UTC, ramonmendes-mlb commented on angular.json
> +    "analytics": "41042630-0b5e-4b62-b5cf-8b2517ea89e9"
Vc setou algum analitycs ?

2022-09-18 20:37 UTC, ramonmendes-mlb requested changes

2022-09-18 20:37 UTC, ramonmendes-mlb commented on src/app/components/template/header/header.component.spec.ts
> +  it('should create', () => {
Cabe escrever um test unitario do metodo toggleDrawer.

2022-09-18 20:37 UTC, ramonmendes-mlb commented on src/app/services/drawer.service.ts
> +  toggle():void {
Criar teste unitario.

2022-09-18 20:37 UTC, ramonmendes-mlb commented on src/app/services/drawer.service.ts
> +  setDrawer(drawer: MatDrawer){
Criar Test unitario

2022-09-18 20:37 UTC, ramonmendes-mlb commented on src/styles.scss
> +height: 100%;
```suggestion
     height: 100%; 
```
Coloca tabulacao aqui ... vou acrescentar um linter no codigo ... 
os atributos de dentro de chaves, sempre bom estar com um espacamento da borda.

2022-09-18 20:37 UTC, ramonmendes-mlb commented on src/styles.scss
> +body {
Mesma coisa aqui ..

2022-09-18 20:40 UTC, amorimluiz commented on angular.json
> +    "analytics": "41042630-0b5e-4b62-b5cf-8b2517ea89e9"
Não, essa linha de comando criou sozinha quando eu dei pull pro meu pc.

2022-09-22 05:06 UTC, merged